name: cctv_streamer_rm19
description: "Aplikasi Kamera Pengawas Pintar Multiplatform - IoT & AI Integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# ---------------------------------------------------------
# Copyright (c) 2026 Mr.Rm19
# Repository: https://github.com/Rm19x
# All rights reserved.
# ---------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  # State Management Terpusat
  provider: ^6.1.1

  # [ 14] Keamanan, Enkripsi AES-256 & Hashing SHA-256
  crypto: ^3.0.3

  # Font Kustom / Icon Pack Tambahan untuk UI Cyber Tech
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # [ 16 & 18] Registrasi Folder Aset untuk File Model Jaringan Saraf Tiruan TFLite (.tflite)
  assets:
    - assets/models/ssd_mobilenet.tflite
    - assets/models/facenet.tflite